---
Name: webpimages
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Assets\Flysystem\PublicAdapter:
    class: WeDevelop\WebpImages\Flysystem\PublicAssetAdapter
  SilverStripe\Assets\Flysystem\ProtectedAdapter:
    class: WeDevelop\WebpImages\Flysystem\ProtectedAssetAdapter

SilverStripe\Assets\Storage\DBFile:
  extensions:
    - WeDevelop\WebpImages\Storage\DBFileExtension

SilverStripe\Assets\File:
  allowed_extensions:
    - webp
